service: runpod-manager


provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 256
  timeout: 30
  environment:
    RUNPOD_API_KEY: ${ssm:/runpod/api_key}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/runpod/api_key

functions:
  runpodManager:
    handler: lambda_handler.lambda_handler
    description: RunPod management functions
    events:
      - http:
          path: /runpod
          method: post
          cors: true

package:
  patterns:
    - '!venv/**'
    - '!node_modules/**'
    - '!.env'
    - '!.git/**'
    - '!*.sh'
    - lambda_handler.py
    - runpod_manager.py

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    slim: true
    noDeploy:
      - pytest
      - boto3
      - botocore
